import "./globals.css";
import { Inter } from "next/font/google";
import Sidebar from "./components/Sidebar";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: {
  children?: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <React.Fragment>
          <div className="h-screen flex flex-row justify-start">
            <Sidebar/>
            <div className="flex-1 p-4 bg-blue-950 text-white border-1 border-dashed">{children}</div>
          </div>
        </React.Fragment>        
      </body>
    </html>
  );
}
